name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  # If the event is type of "push"
  PUSH_EVENT: ${{ github.event_name == 'push' }}

  # Whether to skip the tagging
  SKIP_TAG: ${{ !contains(join(fromJson(toJson(github.event.commits)), ' '), '#skip') }}

jobs:
  validate:
    name: Run lint, unit and end-to-end tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Install Playwright dependencies
        run: npx playwright install --with-deps
      - name: Run end-to-end tests with Playwright
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      # Only deploy on push events
      - if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag:
    name: Tag the release
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      # Skip if the commit message contains '#skip'
      # Otherwise, only run on push events
      - if: ${{ github.event_name == 'push' && !contains(join(fromJson(toJson(github.event.commits)), ' '), '#skip') }}
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
